model_name_or_path: None

model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

dataset_name: None

dataset_prompt_column: problem
system_prompt: "You will be given one 'source text' and one 'task description' about how you should do to rewritten that 'source text'." #**Please directly return the rewritten content. In addition to including your reasoning within the <think> and </think> tags, make sure that your 'rewritten content' in the formal answer is approximately the same length as the 'source text'.**

vllm_mode: server
vllm_server_host: 127.0.0.1 
vllm_server_port: 8000
vllm_gpu_memory_utilization: 0.0


bf16: true
use_vllm: true 
do_eval: false
gradient_accumulation_steps: 4
gradient_checkpointing: true 
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen3-1.7B-GRPO
hub_strategy: every_save
learning_rate: 1.0e-06 
log_completions: true
log_level: info
logging_first_step: true
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine_with_min_lr
lr_scheduler_kwargs:
  min_lr_rate: 0.1
max_prompt_length: 3000 
max_completion_length: 1500 
max_steps: -1
num_generations: 8 
num_train_epochs: 1
output_dir: None


overwrite_output_dir: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
push_to_hub: false
report_to:
- wandb
reward_funcs:
- wordcountpos
reward_weights:
- 1.0
save_strategy: "steps"
save_steps: 500
save_total_limit: 10
seed: 42
temperature: 0.7 
use_liger_kernel: true 
warmup_ratio: 0.1